<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >


    <!-- Depth camera link -->
    <link name="camera_link">
         <visual>
            <geometry>
                <box size="${lx*0.1} ${ly*0.2} ${le_w}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${lx*0.1} ${ly*0.2} ${le_w}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${lx*0.1}" y="${ly*0.2}" z="${le_w}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="camera_chassis_joint" type="fixed">
        <parent link="chassis"/>
        <child link="camera_link"/>
        <origin xyz="0 0 ${3*le_w/2+lz*1.2}" rpy="0 0 0"/>
    </joint>

    <!-- <link name="camera_optical_frame"/>

    <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_optical_frame"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
    </joint> -->



    <gazebo reference="camera_link">
    <sensor name="camera" type="depth_camera">
        <always_on>true</always_on>
        <update_rate>10</update_rate>
        <visualize>true</visualize>
        <topic>camera</topic>
        <gz_frame_id>camera_link</gz_frame_id>

        <camera>
            <horizontal_fov>1.047</horizontal_fov>
            <image>
                <width>640</width>
                <height>480</height>
                <format>R8G8B8</format>
            </image>
            <clip>
                <near>0.1</near>
                <far>10.0</far>
            </clip>
        </camera>

    </sensor>
    </gazebo>
    
</robot>