<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >


    <!-- Lidar link -->
    <link name="lidar_link">
         <visual>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${le_w}" radius="${rad_w}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="lidar_chassis_joint" type="fixed">
        <parent link="chassis"/>
        <child link="lidar_link"/>
        <origin xyz="0 0 ${le_w/2+lz}" rpy="0 0 0"/>
    </joint>


    <gazebo reference="lidar_link">
    <sensor name="lidar" type="gpu_lidar">
        <always_on>true</always_on>
        <update_rate>10</update_rate>
        <visualize>true</visualize>
        <topic>scan</topic>
        <gz_frame_id>lidar_link</gz_frame_id>

        <lidar>
        <scan>
            <horizontal>
            <samples>720</samples>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
            </horizontal>
            <!-- <vertical>
            <samples>720</samples>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
            </vertical> -->
        </scan>
        <range>
            <min>0.12</min>
            <max>12.0</max>
        </range>
        </lidar>
    </sensor>
    </gazebo>
    
</robot>